export enum CardType {
  LISTENING_DURATION = 'LISTENING_DURATION',

  GENRE = 'GENRE',

  NO_OF_FRIENDS = 'NO_OF_FRIENDS',

  NO_OF_SONGS_LISTENED = 'NO_OF_SONGS_LISTENED',

  TOP_ARTIST = 'TOP_ARTIST',

  TOP_SONG = 'TOP_SONG',

  FRIEND_REQUEST = 'FRIEND_REQUEST',
}
